version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_LISTENERS: SSL://:9092
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka:9092
      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafka1234
      KAFKA_SSL_KEY_PASSWORD: kafka1234
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafka1234
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    volumes:
      - ./ssl:/var/private/ssl
    depends_on:
      - zookeeper

